#############################################################################
# Makefile for building: 2dpainting
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Mar 5 15:56:34 2014
# Project:  2dpainting.pro
# Template: app
# Command: /home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec /home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile 2dpainting.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -I. -I/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtOpenGL -I/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/include -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/usr/X11R6/lib -lQtOpenGL -L/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/lib -L/usr/X11R6/lib64 -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = glwidget.cpp \
		helper.cpp \
		main.cpp \
		window.cpp \
		mesh.cpp moc_glwidget.cpp \
		moc_window.cpp
OBJECTS       = glwidget.o \
		helper.o \
		main.o \
		window.o \
		mesh.o \
		moc_glwidget.o \
		moc_window.o
DIST          = /home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		2dpainting.pro
QMAKE_TARGET  = 2dpainting
DESTDIR       = 
TARGET        = 2dpainting

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: 2dpainting.pro  /home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++/qmake.conf /home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtOpenGL.prl \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl \
		/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl
	$(QMAKE) -spec /home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile 2dpainting.pro
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/declarative_debug.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtOpenGL.prl:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl:
/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile 2dpainting.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/2dpainting1.0.0 || $(MKDIR) .tmp/2dpainting1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/2dpainting1.0.0/ && $(COPY_FILE) --parents glwidget.h helper.h window.h mesh.h .tmp/2dpainting1.0.0/ && $(COPY_FILE) --parents glwidget.cpp helper.cpp main.cpp window.cpp mesh.cpp .tmp/2dpainting1.0.0/ && (cd `dirname .tmp/2dpainting1.0.0` && $(TAR) 2dpainting1.0.0.tar 2dpainting1.0.0 && $(COMPRESS) 2dpainting1.0.0.tar) && $(MOVE) `dirname .tmp/2dpainting1.0.0`/2dpainting1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/2dpainting1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_glwidget.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_glwidget.cpp moc_window.cpp
moc_glwidget.cpp: glwidget.h
	/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) glwidget.h -o moc_glwidget.cpp

moc_window.cpp: helper.h \
		glwidget.h \
		window.h
	/home/tong/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

glwidget.o: glwidget.cpp glwidget.h \
		helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

helper.o: helper.cpp helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helper.o helper.cpp

main.o: main.cpp window.h \
		helper.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

window.o: window.cpp window.h \
		helper.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

mesh.o: mesh.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mesh.o mesh.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

